/* CAMPUSLINK — Admin Interventions Page (Feature 9: At-Risk ML) — Real Data */
const AdminInterventions = (() => {
  let _atRiskStudents = [];

  async function render() {
    const main = document.getElementById('main');
    main.innerHTML = `<div class="page-header"><div class="page-header-content"><div class="page-eyebrow">Loading...</div></div></div>`;

    // Fetch real students and filter at-risk
    const result = await API.get('/students');
    const students = Array.isArray(result?.data) ? result.data : (Array.isArray(result) ? result : []);
    _atRiskStudents = students.filter(s => (s.readiness || 0) < 60).map(s => ({
      name: s.name,
      branch: `${(s.branch || 'CSE').replace('Computer Science & Engineering', 'CSE').replace('Information Technology', 'IT').replace('Electronics & Telecom', 'ETC').replace('Mechanical Engineering', 'ME')} · ${s.year || 2026}`,
      reason: (s.readiness || 0) < 40 ? 'Critical: readiness below 40' : 'Readiness below placement threshold',
      severity: (s.readiness || 0) < 40 ? 'high' : 'medium',
      score: s.readiness || 0,
    }));

    main.innerHTML = `
      <div class="page-header"><div class="page-header-content"><div class="page-eyebrow">At-Risk Student Prediction</div><h1 class="page-title">Intervention Queue</h1><p class="page-subtitle">ML-powered early warning signals for students who may need additional support. Predictions are transparent, reviewable, and never automatic.</p></div></div>
      <div class="insight-card warning mb-6"><strong>⚠️ Advisory Only:</strong> These signals are generated by a scikit-learn GradientBoostingClassifier trained on student engagement patterns. They require human review before any action is taken.</div>
      <div class="flex gap-3 mb-6">
        <button class="btn btn-primary" id="run-atrisk-btn" onclick="AdminInterventions.runMLPrediction()">🤖 Run ML Prediction</button>
        <span class="text-sm text-muted" id="atrisk-source" style="align-self:center">Showing: ${_atRiskStudents.length} at-risk students from database</span>
      </div>
      <div class="stack" id="risk-list">
        ${_atRiskStudents.length ? _renderRiskCards(_atRiskStudents) : '<div class="empty-state"><div class="empty-state-icon">✅</div><div class="empty-state-title">No at-risk students</div><p class="empty-state-text">All students are meeting readiness thresholds.</p></div>'}
      </div>
    `;
  }

  function _renderRiskCards(risk) {
    return risk.map((r, i) => `
      <article class="card card-interactive animate-fade-in-up" style="animation-delay:${i * 80}ms">
        <div class="flex justify-between items-center">
          <div class="flex items-center gap-4">
            <div class="avatar avatar-lg ${r.severity === 'high' || r.risk_level === 'high' ? 'avatar-orange' : 'avatar-blue'}">${(r.name || 'U').split(' ').map(w=>w[0]).join('')}</div>
            <div>
              <div class="font-bold" style="font-size:16px">${r.name}</div>
              <div class="text-sm text-muted">${r.branch || ''}</div>
              <div class="text-sm mt-2">${r.reason || ''}</div>
              ${r.risk_factors ? `<div class="mt-2">${r.risk_factors.map(f => `<div class="text-xs text-muted">• <strong>${f.factor}:</strong> ${AIText.formatInline(f.explanation)}</div>`).join('')}</div>` : ''}
              ${r.recommended_actions ? `<div class="mt-2"><div class="text-xs font-bold text-accent">Recommended:</div>${r.recommended_actions.map(a => `<div class="text-xs text-muted">→ ${a}</div>`).join('')}</div>` : ''}
            </div>
          </div>
          <div class="text-center">
            ${ScoreRing.render(r.score || Math.round((1 - (r.risk_probability || 0.5)) * 100), { size: 80, label: r.risk_probability !== undefined ? 'safe' : 'readiness' })}
            ${r.risk_probability !== undefined ? `<div class="text-xs text-muted mt-1">Risk: ${Math.round(r.risk_probability * 100)}%</div>` : ''}
          </div>
        </div>
        <div class="flex gap-3 mt-4" style="justify-content:flex-end">
          <span class="badge badge-${(r.severity || r.risk_level) === 'high' ? 'danger' : 'warning'}">${r.severity || r.risk_level || 'medium'} priority</span>
          <button class="btn btn-sm btn-primary" onclick="AdminInterventions.openScheduleModal('${esc(r.name)}')">Schedule Check-in</button>
          <button class="btn btn-sm btn-ghost" onclick="AdminInterventions.markReviewed('${esc(r.name)}')">Mark Reviewed</button>
        </div>
      </article>
    `).join('');
  }

  function openScheduleModal(studentName) {
    const modalId = 'modal-sched-checkin';
    const existing = document.getElementById(modalId);
    if (existing) existing.remove();

    const overlay = document.createElement('div');
    overlay.id = modalId;
    overlay.style.cssText = 'position:fixed;inset:0;background:rgba(0,0,0,0.7);backdrop-filter:blur(4px);z-index:9999;display:flex;align-items:center;justify-content:center;padding:16px;';
    overlay.onclick = (e) => { if (e.target === overlay) overlay.remove(); };
    overlay.innerHTML = `
      <div class="card animate-fade-in-up" style="background:#111827;border:1px solid rgba(255,255,255,0.15);border-radius:16px;max-width:480px;width:100%;padding:24px;box-shadow:0 25px 50px -12px rgba(0,0,0,0.7);">
        <div class="flex justify-between items-center mb-4 pb-2" style="border-bottom:1px solid rgba(255,255,255,0.08)">
          <div>
            <h3 style="margin:0;font-size:18px;color:#f8fafc;">📅 Schedule Student Check-in</h3>
            <p class="text-xs text-muted" style="margin:3px 0 0 0">Intervention counseling session with <strong>${esc(studentName)}</strong></p>
          </div>
          <button class="btn btn-sm btn-ghost" onclick="document.getElementById('${modalId}').remove()">✕</button>
        </div>
        <div class="form-group mb-3">
          <label class="form-label" style="font-size:12.5px;color:#cbd5e1;display:block;margin-bottom:6px;">Meeting Date & Time</label>
          <input type="datetime-local" id="checkin-datetime" class="form-input" value="${new Date(Date.now() + 86400000 * 2).toISOString().slice(0, 16)}" style="width:100%;padding:9px 12px;background:rgba(255,255,255,0.05);border:1px solid rgba(255,255,255,0.15);border-radius:8px;color:#fff;">
        </div>
        <div class="form-group mb-4">
          <label class="form-label" style="font-size:12.5px;color:#cbd5e1;display:block;margin-bottom:6px;">Guidance Focus Area</label>
          <select id="checkin-topic" class="form-select" style="width:100%;padding:9px 12px;background:rgba(255,255,255,0.05);border:1px solid rgba(255,255,255,0.15);border-radius:8px;color:#fff;">
            <option value="Resume & Skill Gap Remediation">Resume & Skill Gap Remediation</option>
            <option value="Mock Interview & Communication Prep">Mock Interview & Communication Prep</option>
            <option value="Academic Backlog & Eligibility Counseling">Academic Backlog & Eligibility Counseling</option>
            <option value="Aptitude & Technical Practice Drills">Aptitude & Technical Practice Drills</option>
          </select>
        </div>
        <div class="flex justify-end gap-2">
          <button class="btn btn-sm btn-secondary" onclick="document.getElementById('${modalId}').remove()">Cancel</button>
          <button class="btn btn-sm btn-primary" id="btn-confirm-checkin">Schedule & Send Calendar Invite</button>
        </div>
      </div>
    `;
    document.body.appendChild(overlay);

    document.getElementById('btn-confirm-checkin')?.addEventListener('click', async () => {
      const topic = document.getElementById('checkin-topic')?.value;
      try {
        await API.post('/students/all/interventions', {
          title: `1-on-1 Check-in: ${topic}`,
          type: 'meeting',
          priority: 'high',
          notes: `Check-in scheduled for ${studentName} covering ${topic}`
        });
      } catch (_e) {}
      Toast.success(`Check-in scheduled with ${studentName}! Invitation sent.`);
      overlay.remove();
    });
  }

  function markReviewed(studentName) {
    const student = _atRiskStudents.find(s => s.name === studentName);
    if (student) {
      student.severity = 'resolved';
      student.reason = '✓ Reviewed by Placement Officer — Mentorship assigned';
    }
    Toast.success(`Marked as reviewed: ${studentName}`);
    const el = document.getElementById('risk-list');
    if (el) el.innerHTML = _renderRiskCards(_atRiskStudents);
  }

  async function runMLPrediction() {
    const btn = document.getElementById('run-atrisk-btn');
    btn.textContent = '🤖 Analyzing...'; btn.disabled = true;

    const results = [];
    for (const student of _atRiskStudents) {
      const result = await API.post('/ai/at-risk', {
        readinessScore: student.score || 50,
        readinessTrend: student.severity === 'high' ? -9 : -3,
        daysInactive: 7,
        profileCompletion: 60,
        applicationsCount: 2,
        cgpa: 6.8,
        aptitudeScore: student.score < 50 ? 40 : 55,
        interviewScore: 50,
      });

      results.push({
        name: student.name,
        branch: student.branch,
        score: student.score,
        severity: result.risk_level || student.severity,
        risk_level: result.risk_level || 'medium',
        risk_probability: result.risk_probability || 0.5,
        reason: student.reason,
        risk_factors: result.risk_factors || [],
        recommended_actions: result.recommended_actions || [],
      });
    }

    btn.textContent = '🤖 Run ML Prediction'; btn.disabled = false;

    const source = results[0]?.risk_factors?.length > 0 ? 'Logistic Regression ML' : 'rule-based';
    document.getElementById('atrisk-source').textContent = `Showing: ${source} predictions`;
    document.getElementById('risk-list').innerHTML = results.length ? _renderRiskCards(results) : '<div class="empty-state"><div class="empty-state-icon">✅</div><div class="empty-state-title">No at-risk students</div></div>';
  }

  return { render, runMLPrediction, openScheduleModal, markReviewed };
})();

