/* CAMPUSLINK — Admin Interventions Page (Feature 9: At-Risk ML) */
const AdminInterventions = (() => {
  async function render() {
    // Use demo data initially, then try AI service
    const risk = API.DEMO.admin.risk;
    document.getElementById('main').innerHTML = `
      <div class="page-header"><div class="page-header-content"><div class="page-eyebrow">At-Risk Student Prediction</div><h1 class="page-title">Intervention Queue</h1><p class="page-subtitle">ML-powered early warning signals for students who may need additional support. Predictions are transparent, reviewable, and never automatic.</p></div></div>
      <div class="insight-card warning mb-6"><strong>⚠️ Advisory Only:</strong> These signals are generated by a scikit-learn GradientBoostingClassifier trained on student engagement patterns. They require human review before any action is taken. No high-stakes decisions are automated.</div>
      <div class="flex gap-3 mb-6">
        <button class="btn btn-primary" id="run-atrisk-btn" onclick="AdminInterventions.runMLPrediction()">🤖 Run ML Prediction</button>
        <span class="text-sm text-muted" id="atrisk-source" style="align-self:center">Showing: static demo data</span>
      </div>
      <div class="stack" id="risk-list">
        ${_renderRiskCards(risk)}
      </div>
    `;
  }

  function _renderRiskCards(risk) {
    return risk.map((r, i) => `
      <article class="card card-interactive animate-fade-in-up" style="animation-delay:${i * 80}ms">
        <div class="flex justify-between items-center">
          <div class="flex items-center gap-4">
            <div class="avatar avatar-lg ${r.severity === 'high' || r.risk_level === 'high' ? 'avatar-orange' : 'avatar-blue'}">${(r.name || 'U').split(' ').map(w=>w[0]).join('')}</div>
            <div>
              <div class="font-bold" style="font-size:16px">${r.name}</div>
              <div class="text-sm text-muted">${r.branch || ''}</div>
              <div class="text-sm mt-2">${r.reason || ''}</div>
              ${r.risk_factors ? `<div class="mt-2">${r.risk_factors.map(f => `<div class="text-xs text-muted">• <strong>${f.factor}:</strong> ${f.explanation}</div>`).join('')}</div>` : ''}
              ${r.recommended_actions ? `<div class="mt-2"><div class="text-xs font-bold text-accent">Recommended:</div>${r.recommended_actions.map(a => `<div class="text-xs text-muted">→ ${a}</div>`).join('')}</div>` : ''}
            </div>
          </div>
          <div class="text-center">
            ${ScoreRing.render(r.score || Math.round((1 - (r.risk_probability || 0.5)) * 100), { size: 80, label: r.risk_probability !== undefined ? 'safe' : 'readiness' })}
            ${r.risk_probability !== undefined ? `<div class="text-xs text-muted mt-1">Risk: ${Math.round(r.risk_probability * 100)}%</div>` : ''}
          </div>
        </div>
        <div class="flex gap-3 mt-4" style="justify-content:flex-end">
          <span class="badge badge-${(r.severity || r.risk_level) === 'high' ? 'danger' : 'warning'}">${r.severity || r.risk_level || 'medium'} priority</span>
          <button class="btn btn-sm" onclick="Toast.info('Scheduling check-in with ${r.name}')">Schedule Check-in</button>
          <button class="btn btn-sm btn-ghost" onclick="Toast.info('Reviewed — ${r.name} flagged as reviewed')">Mark Reviewed</button>
        </div>
      </article>
    `).join('');
  }

  async function runMLPrediction() {
    const btn = document.getElementById('run-atrisk-btn');
    btn.textContent = '🤖 Analyzing...'; btn.disabled = true;

    // Run ML prediction for each student in the demo data
    const students = API.DEMO.admin.risk;
    const results = [];

    for (const student of students) {
      const result = await API.post('/ai/at-risk', {
        readinessScore: student.score || 50,
        readinessTrend: student.severity === 'high' ? -9 : -3,
        daysInactive: student.reason?.includes('21 days') ? 21 : student.reason?.includes('inactiv') ? 14 : 3,
        profileCompletion: student.reason?.includes('incomplete') ? 40 : 70,
        applicationsCount: 2,
        cgpa: 6.8,
        aptitudeScore: student.reason?.includes('aptitude') ? 40 : 65,
        interviewScore: 50,
      });

      results.push({
        name: student.name,
        branch: student.branch,
        score: student.score,
        severity: result.risk_level || student.severity,
        risk_level: result.risk_level || 'medium',
        risk_probability: result.risk_probability || 0.5,
        reason: student.reason,
        risk_factors: result.risk_factors || [],
        recommended_actions: result.recommended_actions || [],
      });
    }

    btn.textContent = '🤖 Run ML Prediction'; btn.disabled = false;

    const source = results[0]?.risk_factors?.length > 0 ? 'scikit-learn GBC' : 'demo data';
    document.getElementById('atrisk-source').textContent = `Showing: ${source} predictions`;
    document.getElementById('risk-list').innerHTML = _renderRiskCards(results);
  }

  return { render, runMLPrediction };
})();
